## Linear Regression - Closed Form Solution Vs Solution using Gradient Descent Algorithm

In [15]:
#Linear Regression
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import math
import os

In [16]:
#For linear Regression using the statsmodels package
import statsmodels.api as stm
import math

### Data: Cars.csv

In [17]:
#Setting the working directory
# os.chdir("C:/Users/Gourab/Desktop/R")
os.chdir("C:\\Users\\MANDY\\Desktop\\dataset")

#Reading the data
cars = pd.read_csv("cars.csv")

In [18]:
X = cars[['Weight', 'Horsepower', 'Displacement']]
X = stm.add_constant(X)
y = cars['MPG']

In [19]:
X.head()

const  Weight  Horsepower  Displacement
0    1.0    3504         130         307.0
1    1.0    3693         165         350.0
2    1.0    3436         150         318.0
3    1.0    3433         150         304.0
4    1.0    3449         140         302.0

### Linear Regression - Statsmodels Solution

In [20]:
model = stm.OLS(y,X).fit()
model.params


const           44.499978
Weight          -0.005313
Horsepower      -0.039377
Displacement    -0.007919
dtype: float64

### Linear Regression - Closed Form Solution (Using Matrix)

In [21]:
#Converting the Data Frames into matrix
X = X.as_matrix()
y = y.as_matrix()

In [22]:
#Transpose of X
tX = np.transpose(X)

In [23]:
#Closed form solution for the coefficients
np.matmul(np.matmul(np.linalg.inv(np.matmul(tX,X)), tX),y)

array([ 4.44999776e+01, -5.31300288e-03, -3.93767539e-02, -7.91897363e-03])

### Non-Invertibility of a Matrix

In [26]:
h = np.array([[1,3,5],
             [2,9,9],
             [2.5,7.5,12.5]])    #Note: Col3 = 2.5*Col1

h = np.transpose(h)

In [27]:
#Inverse of the matrix
np.linalg.inv(h)

array([[ 3.24259173e+16, -1.80143985e+15, -5.40431955e+15],
       [-4.00000000e+00,  5.00000000e-01,  5.00000000e-01],
       [-1.29703669e+16,  7.20575940e+14,  2.16172782e+15]])

In [28]:
np.linalg.det(h)

1.387778780781442e-15

In [29]:
#Deterninant of the product of tX and X
np.linalg.det(np.matmul(np.transpose(h),h))

4.055783486833766e-12

**Note** This is a problem that can be caused due to the presence of multicollinearity...

### Simple Linear Regression - with Gradient Descent

In [5]:
mtcars.head()

mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
0  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4     4
1  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4     4
2  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4     1
3  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3     1
4  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3     2

In [6]:
#X and y
X = mtcars[['wt']]
X = stm.add_constant(X)
y = mtcars['mpg']

X = X.as_matrix()
y = y.as_matrix()

C:\Users\Gourab\Anaconda3\lib\site-packages\numpy\core\fromnumeric.py:2389: FutureWarning: Method .ptp is deprecated and will be removed in a future version. Use numpy.ptp instead.
  return ptp(axis=axis, out=out, **kwargs)
C:\Users\Gourab\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  
C:\Users\Gourab\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  import sys


In [9]:
print(X.shape)
print(y.shape)

(32, 2)
(32, 1)


In [8]:
y=y.reshape(32,1)

In [10]:
#Initialize the weight vector
weight = np.array([[0],[0]])

#Fix a atep size
alpha = 0.0025

#Optimization

for i in range(1,1000):
    delta = np.matmul(np.transpose(X), (y - np.matmul(X,weight)))
    #print(delta)
    weight = weight - (-2)*alpha*delta


weight

array([[37.28494997],
       [-5.34442097]])

#### Cross-Checks

In [11]:
model = stm.OLS(y,X).fit()

In [12]:
model.params

array([37.28512617, -5.34447157])

### One Challenge - Gradient Descent may go Crazzy without Feature Scaling!

In [13]:
#X and y
X = cars[['Weight']]
X = stm.add_constant(X)
y = cars['MPG']

X = X.as_matrix()
y = y.as_matrix()

C:\Users\Gourab\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  
C:\Users\Gourab\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  import sys


In [14]:
y.shape

(406,)

In [15]:
y=y.reshape(406,1)

In [16]:
#Initialize the weight vector
weight = np.array([[0],[0]])


#Fix a atep size
alpha = 0.000000001


#Optimization
for i in range(1,100000000):
    delta = np.matmul(np.transpose(X), (y - np.matmul(X,weight)))
    #print(delta)
    weight = weight - (-2)*alpha*delta


weight

C:\Users\Gourab\Anaconda3\lib\site-packages\ipykernel_launcher.py:11: RuntimeWarning: overflow encountered in matmul
  # This is added back by InteractiveShellApp.init_path()
C:\Users\Gourab\Anaconda3\lib\site-packages\ipykernel_launcher.py:11: RuntimeWarning: invalid value encountered in matmul
  # This is added back by InteractiveShellApp.init_path()
C:\Users\Gourab\Anaconda3\lib\site-packages\ipykernel_launcher.py:13: RuntimeWarning: invalid value encountered in subtract
  del sys.path[0]


KeyboardInterrupt: 

### Muliple Linear Regression - Gradient Descent with Feature Scaling

In [17]:
cars_scaled = cars[['MPG','Weight','Horsepower']].apply(lambda x: (x - np.min(x)) / (np.max(x) - np.min(x)))

In [18]:
cars_scaled.head()

MPG    Weight  Horsepower
0  0.386266  0.536150    0.565217
1  0.321888  0.589736    0.717391
2  0.386266  0.516870    0.652174
3  0.343348  0.516019    0.652174
4  0.364807  0.520556    0.608696

In [19]:
#X and y
X = cars_scaled[['Weight']]
X = stm.add_constant(X)
y = cars_scaled['MPG']

X = X.as_matrix()
y = y.as_matrix()
y=y.reshape(406,1)

C:\Users\Gourab\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  
C:\Users\Gourab\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  import sys


In [20]:
#Initialize the weight vector
weight = np.array([[0],[0]])


#Fix a atep size
alpha = 0.001


#Optimization
for i in range(1,80000):
    delta = np.matmul(np.transpose(X), (y - np.matmul(X,weight)))
    #print(delta)
    weight = weight - (-2)*alpha*delta


weight

array([[ 0.72371563],
       [-0.59123635]])

In [21]:
model = stm.OLS(y,X).fit()
model.params

array([ 0.72371563, -0.59123635])

### GRADIENT DESCENT FUNCTION WITH SCALED (STANDARDISED) FEATURES

In [22]:
cars_scaled2 = cars[['MPG','Weight','Horsepower']].apply(lambda x: (x - np.mean(x)) / np.std(x))

In [23]:
cars_scaled2.mean()

MPG          -8.485276e-16
Weight       -6.699622e-18
Horsepower    3.809213e-16
dtype: float64

In [24]:
cars_scaled2.std()

MPG           1.001234
Weight        1.001234
Horsepower    1.001234
dtype: float64

In [25]:
#X and y
X = cars_scaled2[['Weight']]
X = stm.add_constant(X)
y = cars_scaled2['MPG']

X = X.as_matrix()
y = y.as_matrix()
y=y.reshape(406,1)

C:\Users\Gourab\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  
C:\Users\Gourab\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  import sys


In [26]:
#Initialize the weight vector
weight = np.array([[0],[0]])


#Fix a atep size
alpha = 0.001


#Optimization
for i in range(1,100000):
    delta = np.matmul(np.transpose(X), (y - np.matmul(X,weight)))
    #print(delta)
    weight = weight - (-2)*alpha*delta


weight

array([[-8.10018719e-16],
       [-7.87509941e-01]])

In [27]:
model = stm.OLS(y,X).fit()
model.params

array([-6.90419943e-16, -7.87509941e-01])

### GRADIENT DESCENT FUNCTION WITH SCALED (STANDARDISED) FEATURES [USING WHILE LOOP]

In [28]:
cars_scaled2 = cars[['MPG','Weight','Horsepower']].apply(lambda x: (x - np.mean(x)) / np.std(x))

In [29]:
#X and y
X = cars_scaled2[['Weight']]
X = stm.add_constant(X)
y = cars_scaled2['MPG']

X = X.as_matrix()
y = y.as_matrix()
y=y.reshape(406,1)

C:\Users\Gourab\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  
C:\Users\Gourab\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  import sys


In [32]:
#Initialize the weight vector
weight = np.array([[0],[0]])


#Fix a atep size
alpha = 0.001
delta = 1
tolerance = 10e-10
count = 0

#Optimization
while np.sum(delta**2) > tolerance :
    delta = np.matmul(np.transpose(X), (y - np.matmul(X,weight)))
    weight = weight - (-2)*alpha*delta
    count += 1

print(count)
print(weight)

11
[[-8.22897306e-16]
 [-7.87509932e-01]]


### PREDICTION USING THE COEFFICIENTS

In [ ]:
#Getting the fitted values
pred = np.matmul(X,weight)
pred[:10]

In [ ]:
pred2 = model.fittedvalues
pred2[:10]

Note that given a new  data we need to scale the data and add a constant column then use it to make prediction in the same way as above