In [2]:
import numpy as np
import pandas as pd
import matplotlib as pyplot
#For test-train split
from sklearn.model_selection import train_test_split

In [4]:
import os

data=pd.read_csv('iris.csv')

In [5]:
from sklearn.model_selection import train_test_split
train_X, test_X, train_y, test_y = train_test_split(data.iloc[:,:-1], data.iloc[:,-1], test_size = 0.3, stratify=data.iloc[:,-1], random_state = 13)

In [6]:
#eculiean distance
def Eu_dist(x1,x2):
    return (np.sqrt(np.sum(x1-x2)**2))

In [7]:
#step 1
def knn(train_X,train_y,obs):
    d=[]
    length_train = train_X.shape[0]

    for i in range (0,length_train):
        d.append((Eu_dist(train_X.iloc[i,],obs),train_X.index[i]))
    d.sort(key=lambda x: x[0])
    min_dist=train_y[d[0][1]]
    return(min_dist)

In [8]:
out=knn(train_X,train_y,test_X.iloc[41,])
out

'Iris-virginica'

In [14]:
#step 1
length_train = train_X.shape[0]
obs=test_X.iloc[2,]
d=[]
for i in range (0,length_train):
    d.append((Eu_dist(train_X.iloc[i,],obs),i))
print(d)

[(8.5, 0), (36.1, 1), (58.5, 2), (32.0, 3), (9.2, 4), (59.2, 5), (60.800000000000004, 6), (82.30000000000001, 7), (65.60000000000001, 8), (0.9999999999999996, 9), (48.800000000000004, 10), (69.4, 11), (54.599999999999994, 12), (18.9, 13), (48.5, 14), (44.6, 15), (21.3, 16), (5.0, 17), (67.60000000000001, 18), (10.9, 19), (45.9, 20), (43.599999999999994, 21), (37.29999999999999, 22), (51.1, 23), (5.6, 24), (40.00000000000001, 25), (16.900000000000002, 26), (26.200000000000003, 27), (32.5, 28), (0.8000000000000003, 29), (53.800000000000004, 30), (65.0, 31), (13.3, 32), (43.4, 33), (60.89999999999999, 34), (23.400000000000002, 35), (58.3, 36), (82.60000000000002, 37), (43.5, 38), (12.200000000000001, 39), (9.5, 40), (17.6, 41), (0.6000000000000003, 42), (1.0000000000000004, 43), (77.10000000000001, 44), (49.89999999999999, 45), (78.60000000000001, 46), (26.8, 47), (42.699999999999996, 48), (71.50000000000001, 49), (23.700000000000003, 50), (35.400000000000006, 51), (61.300000000000004, 52

In [10]:
test_y.iloc[41,]

'Iris-virginica'

In [9]:
def knn2(train_X,train_y,test_X,test_y):
    predicted=[]
    test_y['out']=np.nan
    #test_y['out']=np.nan
    length_train = train_X.shape[0]
    length_test = test_X.shape[0]
    for j in range (0,length_test):
        d=[]
        for i in range(0,length_train):
            d.append((Eu_dist(train_X.iloc[i,],test_X.iloc[j,]),train_X.index[i]))
        d.sort(key=lambda x: x[0])
        predicted.append(train_y[d[0][1]])
    return(predicted)

In [10]:
output=knn2(train_X,train_y,test_X,test_y)

In [54]:
len(train_X)

112

In [55]:
len(train_y)

112

In [56]:
len(test_X)

38

In [57]:
len(test_y)

38

In [17]:
output

['Iris-versicolor',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-setosa',
 'Iris-virginica',
 'Iris-setosa',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-virginica',
 'Iris-versicolor',
 'Iris-virginica',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-virginica',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-setosa',
 'Iris-virginica',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-virginica',
 'Iris-versicolor',
 'Iris-virginica',
 'Iris-virginica',
 'Iris-setosa',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-setosa',
 'Iris-virginica',
 'Iris-virginica',
 'Iris-virginica',
 'Iris-versicolor',
 'Iris-virginica',
 'Iris-virginica',
 'Iris-virginica',
 'Iris-setosa',
 'Iris-virginica']

In [13]:
test_y['out']=pd.Series(output)

In [15]:
train_X, test_X, train_y, test_y = train_test_split(data.iloc[:,:-1], data.iloc[:,-1], test_size = 0.25, stratify=data.iloc[:,-1], random_state = 13)

In [16]:
df=pd.concat([test_y,pd.DataFrame(output,columns=['col1'])],axis=1,ignore_index=True)
df.shape

(71, 2)

In [34]:
test_y.head()

55    Iris-versicolor
78    Iris-versicolor
80    Iris-versicolor
2         Iris-setosa
25        Iris-setosa
Name: Species, dtype: object

In [36]:
type(test_y)

pandas.core.series.Series

In [ ]:
## 3NN
## get first 3 index
## we will get y laues of array
## get mode
## we will get values

In [19]:
def getAccuracy(testSet, predictions):
    correct = 0
    for x in range(len(testSet)):
        if testSet[x][-1] is predictions[x]:
            correct += 1
    return (correct/float(len(testSet))) * 100.0

In [20]:
#Testing getAccuracy function
testSet = [[1,1,1,'a'], [2,2,2,'a'], [3,3,3,'b']]
predictions = ['a', 'a', 'a']
accuracy = getAccuracy(testSet, predictions)
print(accuracy)

66.66666666666666


In [ ]:
## bootstarpping pre learning

In [33]:
#3 knn
def knn3(train_X,train_y,test_X,test_y):
    predicted=[]
    test_y['out']=np.nan
    #test_y['out']=np.nan
    length_train = train_X.shape[0]
    length_test = test_X.shape[0]
    for j in range (0,length_test):
        d=[]
        for i in range(0,length_train):
            d.append((Eu_dist(train_X.iloc[i,],test_X.iloc[j,]),train_X.index[i]))
        d.sort(key=lambda x: x[0])
        predicted.append(train_y[d[0][1]])
    return(predicted)

In [59]:
output=knn3(train_X,train_y,test_X,test_y)

In [60]:
test_y['out']=pd.Series(output)

In [61]:
test_X['output']=pd.Series(output)

In [62]:
train_X, test_X, train_y, test_y = train_test_split(data.iloc[:,:-1], data.iloc[:,-1], test_size = 0.25, stratify=data.iloc[:,-1], random_state = 13)

In [63]:
df=pd.concat([test_y,pd.DataFrame(output,columns=['col1'])],axis=1,ignore_index=True)
df.shape

(66, 2)

In [85]:
# Python script for confusion matrix creation. 
from sklearn.metrics import confusion_matrix 
from sklearn.metrics import accuracy_score 
from sklearn.metrics import classification_report 
actual = test_y
predicted =output
results = confusion_matrix(actual, predicted) 
print ('Confusion Matrix ')
print(results) 
print ('Accuracy Score ',accuracy_score(actual, predicted)) 
print ('Report  ')
print (classification_report(actual, predicted) )


Confusion Matrix 
[[13  0  0]
 [ 0 12  0]
 [ 0  0 13]]
Accuracy Score  1.0
Report  
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        13
Iris-versicolor       1.00      1.00      1.00        12
 Iris-virginica       1.00      1.00      1.00        13

    avg / total       1.00      1.00      1.00        38



In [64]:
# recheck
def getAccuracy(testSet, predictions):
    correct = 0
    for x in range(len(testSet)):
        if testSet[x][-1] is predictions[x]:
            correct += 1
    return (correct/float(len(testSet))) * 100.0

In [65]:
#Testing getAccuracy function
testSet = [[1,1,1,'a'], [2,2,2,'a'], [3,3,3,'b']]
predictions = ['a', 'a', 'a']
accuracy = getAccuracy(testSet, predictions)
print(accuracy)

66.66666666666666


In [ ]:
# now i have no. of n term
def knn_n(train_X,train_y,test_X,test_y):
    predicted=[]
    test_y['out']=np.nan
    #test_y['out']=np.nan
    length_train = train_X.shape[0]
    length_test = test_X.shape[0]
    for j in range (0,length_test):
        d=[]
        for i in range(0,length_train):
            d.append((Eu_dist(train_X.iloc[i,],test_X.iloc[j,]),train_X.index[i]))
        d.sort(key=lambda x: x[0])
        predicted.append(train_y[d[0][1]])
    return(predicted)

In [92]:
# now i have no. of n term
from scipy import stats
def knn_n(train_X,train_y,test_X,test_y):
    predicted=[]
    test_y['out']=np.nan
    #test_y['out']=np.nan
    length_train = train_X.shape[0]
    length_test = test_X.shape[0]
    for j in range (0,length_test):
        d=[]
        for i in range(0,length_train):
            d.append((Eu_dist(train_X.iloc[i,],test_X.iloc[j,]),train_X.index[i]))
        d.sort(key=lambda x: x[0])
        #mode
        predicted.append(mode(top_n),[0])
        for s in range(0,nterm):
            d1=[]
            #for index and eculiean 
            d1.append((Eu_dist(train_X.iloc[s,],obs),test_X.iloc[s,],test_y.iloc[s,],train_X.index[s])
            d1.sort(key=lambda x: x[0])
            predicted.append(train_y[d1[0][1]]
    return(predicted)
                         #slice top_n = d[0:nterm]

SyntaxError: invalid syntax (<ipython-input-92-deba1672bb93>, line 20)

In [75]:
def knn_n(nterm,train_X,train_y,test_X,test_y):
    predicted=[]
    length_train = train_X.shape[0]
    length_test = test_X.shape[0]
    for s in range(0,nterm):
        d=[]
        # here index and diastance matrix
        d.append((Eu_dist(train_X.iloc[s,],obs),test_X.iloc[s,],test_y.iloc[s,],train_X.index[s]))
        d.sort(key=lambda x: x[0])
        predicted.append(train_y[d[0][1]])
            

In [109]:
x = (5, 6, 7)
y = (8, 9, 9)
for a, b in zip(x, y):
#     print(a,b)
     eculieandistance = math.sqrt(sum([(a - b) ** 2]))
print("Euclidean distance from x to y: ",distance)

Euclidean distance from x to y:  2.0


In [106]:
import os
os.chdir("C:\\Users\\MANDY\\Desktop\\dataset")
data=pd.read_csv('iris.csv')


In [138]:
from sklearn.model_selection import train_test_split
train_X, test_X, train_y, test_y = train_test_split(data.iloc[:,:-1], data.iloc[:,-1], test_size = 0.25, stratify=data.iloc[:,-1], random_state = 13)

In [139]:
len(train_y)

112

In [140]:
len(train_X)

112

In [141]:
X = train_X # Independent variables
y = test_X
for a,b in zip(X,y):
    print(a,b)
#     eculieandistance = math.sqrt(sum((a - b) ** 2))
# print("Euclidean distance from x to y: ",distance)

Id Id
SepalLengthCm SepalLengthCm
SepalWidthCm SepalWidthCm
PetalLengthCm PetalLengthCm
PetalWidthCm PetalWidthCm


In [126]:
test_X.head(2)

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
55  56            5.7           2.8            4.5           1.3
78  79            6.0           2.9            4.5           1.5

## def knn_n(nterm,train_X,train_y,test_X,test_y):
    Eu_dist = [d,i]
    Eu_dist = train_X-

In [156]:
import os
os.chdir("C:\\Users\\MANDY\\Desktop\\dataset")

data=pd.read_csv('iris.csv')
from sklearn.model_selection import train_test_split
train_X, test_X, train_y, test_y = train_test_split(data.iloc[:,:-1], data.iloc[:,-1], test_size = 0.3, stratify=data.iloc[:,-1], random_state = 13)
#eculiean distance
x1=train_X
x2=train_y
def Eu_dist(x1,x2):
    return (np.sqrt(np.sum(x1-x2)**2))
# print(Eu_dist)

<function Eu_dist at 0x000002143FDA4A60>
